// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.example.assignment.Protobuf;

public interface AnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.AnimalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 regNum = 1;</code>
   */
  int getRegNum();

  /**
   * <code>string animalType = 2;</code>
   */
  String getAnimalType();
  /**
   * <code>string animalType = 2;</code>
   */
  com.google.protobuf.ByteString
      getAnimalTypeBytes();

  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   */
  boolean hasDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   */
  com.google.protobuf.Timestamp getDateTime();
  /**
   * <code>.google.protobuf.Timestamp dateTime = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateTimeOrBuilder();

  /**
   * <code>double weight = 4;</code>
   */
  double getWeight();
}
