// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaghterhouse.proto

package com.example.assignment.Protobuf;

/**
 * Protobuf type {@code org.example.AnimalListResponse}
 */
public  final class AnimalListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.example.AnimalListResponse)
        AnimalListResponseOrBuilder {
  // Use AnimalListResponse.newBuilder() to construct.
  private AnimalListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalListResponse() {
    animals_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AnimalListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              animals_ = new java.util.ArrayList<AnimalResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            animals_.add(
                input.readMessage(AnimalResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        animals_ = java.util.Collections.unmodifiableList(animals_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Slaghterhouse.internal_static_org_example_AnimalListResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Slaghterhouse.internal_static_org_example_AnimalListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AnimalListResponse.class, AnimalListResponse.Builder.class);
  }

  public static final int ANIMALS_FIELD_NUMBER = 1;
  private java.util.List<AnimalResponse> animals_;
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  public java.util.List<AnimalResponse> getAnimalsList() {
    return animals_;
  }
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  public java.util.List<? extends AnimalResponseOrBuilder>
      getAnimalsOrBuilderList() {
    return animals_;
  }
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  public int getAnimalsCount() {
    return animals_.size();
  }
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  public AnimalResponse getAnimals(int index) {
    return animals_.get(index);
  }
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  public AnimalResponseOrBuilder getAnimalsOrBuilder(
      int index) {
    return animals_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < animals_.size(); i++) {
      output.writeMessage(1, animals_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < animals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, animals_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AnimalListResponse)) {
      return super.equals(obj);
    }
    AnimalListResponse other = (AnimalListResponse) obj;

    boolean result = true;
    result = result && getAnimalsList()
        .equals(other.getAnimalsList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnimalsCount() > 0) {
      hash = (37 * hash) + ANIMALS_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AnimalListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnimalListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnimalListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnimalListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnimalListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AnimalListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AnimalListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AnimalListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AnimalListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AnimalListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AnimalListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AnimalListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AnimalListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.AnimalListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.AnimalListResponse)
          AnimalListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Slaghterhouse.internal_static_org_example_AnimalListResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Slaghterhouse.internal_static_org_example_AnimalListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnimalListResponse.class, AnimalListResponse.Builder.class);
    }

    // Construct using org.example.AnimalListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnimalsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (animalsBuilder_ == null) {
        animals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        animalsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Slaghterhouse.internal_static_org_example_AnimalListResponse_descriptor;
    }

    public AnimalListResponse getDefaultInstanceForType() {
      return AnimalListResponse.getDefaultInstance();
    }

    public AnimalListResponse build() {
      AnimalListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AnimalListResponse buildPartial() {
      AnimalListResponse result = new AnimalListResponse(this);
      int from_bitField0_ = bitField0_;
      if (animalsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          animals_ = java.util.Collections.unmodifiableList(animals_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.animals_ = animals_;
      } else {
        result.animals_ = animalsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AnimalListResponse) {
        return mergeFrom((AnimalListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AnimalListResponse other) {
      if (other == AnimalListResponse.getDefaultInstance()) return this;
      if (animalsBuilder_ == null) {
        if (!other.animals_.isEmpty()) {
          if (animals_.isEmpty()) {
            animals_ = other.animals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAnimalsIsMutable();
            animals_.addAll(other.animals_);
          }
          onChanged();
        }
      } else {
        if (!other.animals_.isEmpty()) {
          if (animalsBuilder_.isEmpty()) {
            animalsBuilder_.dispose();
            animalsBuilder_ = null;
            animals_ = other.animals_;
            bitField0_ = (bitField0_ & ~0x00000001);
            animalsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnimalsFieldBuilder() : null;
          } else {
            animalsBuilder_.addAllMessages(other.animals_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AnimalListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AnimalListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<AnimalResponse> animals_ =
      java.util.Collections.emptyList();
    private void ensureAnimalsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        animals_ = new java.util.ArrayList<AnimalResponse>(animals_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            AnimalResponse, AnimalResponse.Builder, AnimalResponseOrBuilder> animalsBuilder_;

    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public java.util.List<AnimalResponse> getAnimalsList() {
      if (animalsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(animals_);
      } else {
        return animalsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public int getAnimalsCount() {
      if (animalsBuilder_ == null) {
        return animals_.size();
      } else {
        return animalsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public AnimalResponse getAnimals(int index) {
      if (animalsBuilder_ == null) {
        return animals_.get(index);
      } else {
        return animalsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder setAnimals(
        int index, AnimalResponse value) {
      if (animalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalsIsMutable();
        animals_.set(index, value);
        onChanged();
      } else {
        animalsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder setAnimals(
        int index, AnimalResponse.Builder builderForValue) {
      if (animalsBuilder_ == null) {
        ensureAnimalsIsMutable();
        animals_.set(index, builderForValue.build());
        onChanged();
      } else {
        animalsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder addAnimals(AnimalResponse value) {
      if (animalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalsIsMutable();
        animals_.add(value);
        onChanged();
      } else {
        animalsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder addAnimals(
        int index, AnimalResponse value) {
      if (animalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnimalsIsMutable();
        animals_.add(index, value);
        onChanged();
      } else {
        animalsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder addAnimals(
        AnimalResponse.Builder builderForValue) {
      if (animalsBuilder_ == null) {
        ensureAnimalsIsMutable();
        animals_.add(builderForValue.build());
        onChanged();
      } else {
        animalsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder addAnimals(
        int index, AnimalResponse.Builder builderForValue) {
      if (animalsBuilder_ == null) {
        ensureAnimalsIsMutable();
        animals_.add(index, builderForValue.build());
        onChanged();
      } else {
        animalsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder addAllAnimals(
        Iterable<? extends AnimalResponse> values) {
      if (animalsBuilder_ == null) {
        ensureAnimalsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, animals_);
        onChanged();
      } else {
        animalsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder clearAnimals() {
      if (animalsBuilder_ == null) {
        animals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        animalsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public Builder removeAnimals(int index) {
      if (animalsBuilder_ == null) {
        ensureAnimalsIsMutable();
        animals_.remove(index);
        onChanged();
      } else {
        animalsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public AnimalResponse.Builder getAnimalsBuilder(
        int index) {
      return getAnimalsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public AnimalResponseOrBuilder getAnimalsOrBuilder(
        int index) {
      if (animalsBuilder_ == null) {
        return animals_.get(index);  } else {
        return animalsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public java.util.List<? extends AnimalResponseOrBuilder>
         getAnimalsOrBuilderList() {
      if (animalsBuilder_ != null) {
        return animalsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(animals_);
      }
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public AnimalResponse.Builder addAnimalsBuilder() {
      return getAnimalsFieldBuilder().addBuilder(
          AnimalResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public AnimalResponse.Builder addAnimalsBuilder(
        int index) {
      return getAnimalsFieldBuilder().addBuilder(
          index, AnimalResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .org.example.AnimalResponse animals = 1;</code>
     */
    public java.util.List<AnimalResponse.Builder>
         getAnimalsBuilderList() {
      return getAnimalsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            AnimalResponse, AnimalResponse.Builder, AnimalResponseOrBuilder>
        getAnimalsFieldBuilder() {
      if (animalsBuilder_ == null) {
        animalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                AnimalResponse, AnimalResponse.Builder, AnimalResponseOrBuilder>(
                animals_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        animals_ = null;
      }
      return animalsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.example.AnimalListResponse)
  }

  // @@protoc_insertion_point(class_scope:org.example.AnimalListResponse)
  private static final AnimalListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AnimalListResponse();
  }

  public static AnimalListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalListResponse>
      PARSER = new com.google.protobuf.AbstractParser<AnimalListResponse>() {
    public AnimalListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnimalListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalListResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AnimalListResponse> getParserForType() {
    return PARSER;
  }

  public AnimalListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

