// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.example.assignment.Protobuf;

public interface AnimalListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.AnimalListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  java.util.List<AnimalResponse>
      getAnimalsList();
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  AnimalResponse getAnimals(int index);
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  java.util.List<? extends AnimalResponseOrBuilder>
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .org.example.AnimalResponse animals = 1;</code>
   */
  AnimalResponseOrBuilder getAnimalsOrBuilder(
      int index);
}
