// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.example.assignment.Protobuf;

public interface AnimalIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.AnimalIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 animalId = 1;</code>
   */
  int getAnimalId();
}
