// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaghterhouse.proto

package com.example.assignment.Protobuf;

public interface DateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.DateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 day = 1;</code>
   */
  int getDay();

  /**
   * <code>int32 month = 2;</code>
   */
  int getMonth();

  /**
   * <code>int32 year = 3;</code>
   */
  int getYear();
}
