// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaghterhouse.proto

package com.example.assignment.Protobuf;

public interface ProductIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.ProductIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 productId = 1;</code>
   */
  int getProductId();
}
