// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaghterhouse.proto

package com.example.assignment.Protobuf;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 productId = 1;</code>
   */
  int getProductId();

  /**
   * <code>string productName = 2;</code>
   */
  String getProductName();
  /**
   * <code>string productName = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string productType = 3;</code>
   */
  String getProductType();
  /**
   * <code>string productType = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();
}
