// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.example.assignment.Protobuf;

public interface ProductListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.ProductListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.ProductResponse products = 1;</code>
   */
  java.util.List<ProductResponse>
      getProductsList();
  /**
   * <code>repeated .org.example.ProductResponse products = 1;</code>
   */
  ProductResponse getProducts(int index);
  /**
   * <code>repeated .org.example.ProductResponse products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .org.example.ProductResponse products = 1;</code>
   */
  java.util.List<? extends ProductResponseOrBuilder>
      getProductsOrBuilderList();
  /**
   * <code>repeated .org.example.ProductResponse products = 1;</code>
   */
  ProductResponseOrBuilder getProductsOrBuilder(
      int index);
}
