// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaghterhouse.proto

package com.example.assignment.Protobuf;

public interface RegisterAnimalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.RegisterAnimalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 regNum = 1;</code>
   */
  int getRegNum();

  /**
   * <code>string animalType = 2;</code>
   */
  String getAnimalType();
  /**
   * <code>string animalType = 2;</code>
   */
  com.google.protobuf.ByteString
      getAnimalTypeBytes();

  /**
   * <code>.google.protobuf.Timestamp dateOfBirth = 3;</code>
   */
  boolean hasDateOfBirth();
  /**
   * <code>.google.protobuf.Timestamp dateOfBirth = 3;</code>
   */
  com.google.protobuf.Timestamp getDateOfBirth();
  /**
   * <code>.google.protobuf.Timestamp dateOfBirth = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOfBirthOrBuilder();

  /**
   * <code>double weight = 4;</code>
   */
  double getWeight();
}
