// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaghterhouse.proto

package com.example.assignment.Protobuf;

public final class Slaghterhouse {
  private Slaghterhouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_RegisterAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_RegisterAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AnimalIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AnimalIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_ProductIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_ProductIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AnimalListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AnimalListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_ProductListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_ProductListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023Slaghterhouse.proto\022\013org.example\032\037goog" +
      "le/protobuf/timestamp.proto\"|\n\025RegisterA" +
      "nimalRequest\022\016\n\006regNum\030\001 \001(\005\022\022\n\nanimalTy" +
      "pe\030\002 \001(\t\022/\n\013dateOfBirth\030\003 \001(\0132\032.google.p" +
      "rotobuf.Timestamp\022\016\n\006weight\030\004 \001(\001\"#\n\017Ani" +
      "malIdRequest\022\020\n\010animalId\030\001 \001(\005\"7\n\013DateRe" +
      "quest\022\013\n\003day\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\014\n\004yea" +
      "r\030\003 \001(\005\"r\n\016AnimalResponse\022\016\n\006regNum\030\001 \001(" +
      "\005\022\022\n\nanimalType\030\002 \001(\t\022,\n\010dateTime\030\003 \001(\0132" +
      "\032.google.protobuf.Timestamp\022\016\n\006weight\030\004 ",
      "\001(\001\"%\n\020ProductIdRequest\022\021\n\tproductId\030\001 \001" +
      "(\005\"N\n\017ProductResponse\022\021\n\tproductId\030\001 \001(\005" +
      "\022\023\n\013productName\030\002 \001(\t\022\023\n\013productType\030\003 \001" +
      "(\t\"B\n\022AnimalListResponse\022,\n\007animals\030\001 \003(" +
      "\0132\033.org.example.AnimalResponse\"E\n\023Produc" +
      "tListResponse\022.\n\010products\030\001 \003(\0132\034.org.ex" +
      "ample.ProductResponse2\210\005\n\rAnimalService\022" +
      "O\n\014createAnimal\022\".org.example.RegisterAn" +
      "imalRequest\032\033.org.example.AnimalResponse" +
      "\022J\n\rgetAnimalById\022\034.org.example.AnimalId",
      "Request\032\033.org.example.AnimalResponse\022M\n\020" +
      "getAnimalsByDate\022\030.org.example.DateReque" +
      "st\032\037.org.example.AnimalListResponse\022Q\n\020g" +
      "etAnimalsByType\022\034.org.example.AnimalIdRe" +
      "quest\032\037.org.example.AnimalListResponse\022S" +
      "\n\022getAnimalsByWeight\022\034.org.example.Anima" +
      "lIdRequest\032\037.org.example.AnimalListRespo" +
      "nse\022N\n\rgetAllAnimals\022\034.org.example.Anima" +
      "lIdRequest\032\037.org.example.AnimalListRespo" +
      "nse\022H\n\014updateAnimal\022\033.org.example.Animal",
      "Response\032\033.org.example.AnimalResponse\022I\n" +
      "\014deleteAnimal\022\034.org.example.AnimalIdRequ" +
      "est\032\033.org.example.AnimalResponse2\375\003\n\016Pro" +
      "ductService\022a\n\037getProductsIncludingAnima" +
      "lRegId\022\034.org.example.AnimalIdRequest\032 .o" +
      "rg.example.ProductListResponse\022M\n\016getPro" +
      "ductById\022\035.org.example.ProductIdRequest\032" +
      "\034.org.example.ProductResponse\022Q\n\016getAllP" +
      "roducts\022\035.org.example.ProductIdRequest\032 " +
      ".org.example.ProductListResponse\022K\n\rcrea",
      "teProduct\022\034.org.example.ProductResponse\032" +
      "\034.org.example.ProductResponse\022K\n\rupdateP" +
      "roduct\022\034.org.example.ProductResponse\032\034.o" +
      "rg.example.ProductResponse\022L\n\rdeleteProd" +
      "uct\022\035.org.example.ProductIdRequest\032\034.org" +
      ".example.ProductResponse2`\n\020SlaughterSer" +
      "vice\022L\n\017slaughterAnimal\022\034.org.example.An" +
      "imalIdRequest\032\033.org.example.AnimalRespon" +
      "seB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_org_example_RegisterAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_RegisterAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_RegisterAnimalRequest_descriptor,
        new String[] { "RegNum", "AnimalType", "DateOfBirth", "Weight", });
    internal_static_org_example_AnimalIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_AnimalIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AnimalIdRequest_descriptor,
        new String[] { "AnimalId", });
    internal_static_org_example_DateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_DateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DateRequest_descriptor,
        new String[] { "Day", "Month", "Year", });
    internal_static_org_example_AnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_AnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AnimalResponse_descriptor,
        new String[] { "RegNum", "AnimalType", "DateTime", "Weight", });
    internal_static_org_example_ProductIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_example_ProductIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_ProductIdRequest_descriptor,
        new String[] { "ProductId", });
    internal_static_org_example_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_example_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_ProductResponse_descriptor,
        new String[] { "ProductId", "ProductName", "ProductType", });
    internal_static_org_example_AnimalListResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_example_AnimalListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AnimalListResponse_descriptor,
        new String[] { "Animals", });
    internal_static_org_example_ProductListResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_example_ProductListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_ProductListResponse_descriptor,
        new String[] { "Products", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
