// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slaughterhouse.proto

package com.example.assignment.Protobuf;

public final class Slaughterhouse {
  private Slaughterhouse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_RegisterAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_RegisterAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AnimalIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AnimalIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_ProductIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_ProductIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AnimalListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AnimalListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_ProductListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_ProductListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024slaughterhouse.proto\022\013org.example\032\037goo" +
      "gle/protobuf/timestamp.proto\"|\n\025Register" +
      "AnimalRequest\022\016\n\006regNum\030\001 \001(\005\022\022\n\nanimalT" +
      "ype\030\002 \001(\t\022/\n\013dateOfBirth\030\003 \001(\0132\032.google." +
      "protobuf.Timestamp\022\016\n\006weight\030\004 \001(\001\"#\n\017An" +
      "imalIdRequest\022\020\n\010animalId\030\001 \001(\005\"7\n\013DateR" +
      "equest\022\013\n\003day\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\014\n\004ye" +
      "ar\030\003 \001(\005\"r\n\016AnimalResponse\022\016\n\006regNum\030\001 \001" +
      "(\005\022\022\n\nanimalType\030\002 \001(\t\022,\n\010dateTime\030\003 \001(\013" +
      "2\032.google.protobuf.Timestamp\022\016\n\006weight\030\004",
      " \001(\001\"%\n\020ProductIdRequest\022\021\n\tproductId\030\001 " +
      "\001(\005\"N\n\017ProductResponse\022\021\n\tproductId\030\001 \001(" +
      "\005\022\023\n\013productName\030\002 \001(\t\022\023\n\013productType\030\003 " +
      "\001(\t\"B\n\022AnimalListResponse\022,\n\007animals\030\001 \003" +
      "(\0132\033.org.example.AnimalResponse\"E\n\023Produ" +
      "ctListResponse\022.\n\010products\030\001 \003(\0132\034.org.e" +
      "xample.ProductResponse2\254\001\n\rAnimalService" +
      "\022O\n\014createAnimal\022\".org.example.RegisterA" +
      "nimalRequest\032\033.org.example.AnimalRespons" +
      "e\022J\n\rgetAnimalById\022\034.org.example.AnimalI",
      "dRequest\032\033.org.example.AnimalResponse2s\n" +
      "\016ProductService\022a\n\037getProductsIncludingA" +
      "nimalRegId\022\034.org.example.AnimalIdRequest" +
      "\032 .org.example.ProductListResponseB\002P\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_org_example_RegisterAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_RegisterAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_RegisterAnimalRequest_descriptor,
        new String[] { "RegNum", "AnimalType", "DateOfBirth", "Weight", });
    internal_static_org_example_AnimalIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_AnimalIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AnimalIdRequest_descriptor,
        new String[] { "AnimalId", });
    internal_static_org_example_DateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_DateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DateRequest_descriptor,
        new String[] { "Day", "Month", "Year", });
    internal_static_org_example_AnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_AnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AnimalResponse_descriptor,
        new String[] { "RegNum", "AnimalType", "DateTime", "Weight", });
    internal_static_org_example_ProductIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_example_ProductIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_ProductIdRequest_descriptor,
        new String[] { "ProductId", });
    internal_static_org_example_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_example_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_ProductResponse_descriptor,
        new String[] { "ProductId", "ProductName", "ProductType", });
    internal_static_org_example_AnimalListResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_example_AnimalListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AnimalListResponse_descriptor,
        new String[] { "Animals", });
    internal_static_org_example_ProductListResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_example_ProductListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_ProductListResponse_descriptor,
        new String[] { "Products", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
